### PR TITLE
Add support for https://osu.ppy.sh/beatmapsets.

### PR DESCRIPTION
**Pull request by hyrious**
Let's try the new osu.ppy.sh. (goto https://osu.ppy.sh/home)
Because he uses react to build the new home page, I use MutationObserver to keep in step with dynamic contents.

### CODE REVIEW

**Comment by h0wXD** [comment]
@hyrious Thanks for the PR! Will take a look at this soon.

**Comment by h0wXD** [comment]
@hyrious Do you mind also adding support for :
- Song page : https://osu.ppy.sh/beatmapsets/598911#osu/1265934
- Logged out users : inject download button for logged out users on both beatmapset and beatmap page?

Thanks for your help!

**Comment by hyrious** [comment]
@h0wXD Sure, I'll look at song page in one day.
BTW, it seems that logged out users won't see the download button. Do you mean to create one in that place?

**Comment by hyrious** [comment]
@h0wXD Now it supports song pages as well as logged out view (just create such button). I haven't tested much.

**Comment by h0wXD** [comment]
@hyrious Looks good! Thanks a lot!

**Pull request merged**
